### ISSUE TITLE
Updating a challenge results in an error

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#63]
**Describe the bug**

**To Reproduce**
1. Go to graphql interface
2. put in the query + variable from the update-challenge sample
2. Execute the querey - get the following error:

"error": {
    "errors": [
      {
        "message": "Variable \"$challengeData\" of required type \"UpdateRootChallengeInput!\" was not provided.",
        "locations": [
          {
            "line": 1,
            "column": 26
          }
        ],
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "GraphQLError: Variable \"$challengeData\" of required type \"UpdateRootChallengeInput!\" was not provided.",
              "    at _loop (/usr/src/app/node_modules/graphql/execution/values.js:94:17)",
              "    at coerceVariableValues (/usr/src/app/node_modules/graphql/execution/values.js:121:16)",
              "    at getVariableValues (/usr/src/app/node_modules/graphql/execution/values.js:50:19)",
              "    at buildExecutionContext (/usr/src/app/node_modules/graphql/execution/execute.js:206:61)",
              "    at executeImpl (/usr/src/app/node_modules/graphql/execution/execute.js:104:20)",
              "    at Object.execute (/usr/src/app/node_modules/graphql/execution/execute.js:63:35)",
              "    at /usr/src/app/node_modules/apollo-server-core/src/requestPipeline.ts:548:22",
              "    at Generator.next (<anonymous>)",
              "    at /usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
              "    at new Promise (<anonymous>)"
            ]
          }
        }
      }
    ]
  }

**Comment by techsmyth** [comment]
Closing as moving away from using deep nested updates
